<?php

    function employee_theme ($existing, $theme, $type, $path) {
        // here employee is file name that we created for twig
        return array(
            'employee' => array(
                'variables' => array(
                    'items' => [],
                    'title' => ''
                )
            )
        );
    }

    function employee_form_alter (&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
        if ($form_id == 'create_employee') {
            //print_r($form['save']); die;
            $form['save']['#value'] = t('Feedback');
        }
    }